spring.application.name=gestor-inventario

app.info.name=Gestor de Inventario
app.info.version=@project.version@
app.info.developer-name=Noelia Mendoza
app.info.developer-email=noelia.mendoza@espe.edu.ec
spring.profiles.active=dev

server.port=8080

# ---- Exploración de propiedades: Logging ----
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/gestor-inventario.log

# ---- Exploración de propiedades: JSON ----
spring.jackson.serialization.indent-output=true

# ---- Exploración de propiedades: Seguridad ----
server.error.include-stacktrace=on_param
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true