spring.application.name=gestor-inventario

app.info.name=Gestor de Inventario
app.info.version=@project.version@
app.info.developer-name=Noelia Mendoza
app.info.developer-email=noelia@example.com
spring.profiles.active=dev